Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,6 +45,9 @@ jobs:
       - name: Install Composer dependencies
         run: composer install --no-progress --no-suggest --prefer-dist
 
+      - name: Run Composer Dump Autoload
+        run: composer dump-autoload
+
       - name: Ensure vendor directory exists
         run: test -d vendor || (echo "Vendor directory not found!" && exit 1)
 
@@ -82,8 +85,7 @@ jobs:
 
       - name: Run migrations and seed database
         run: |
-          php artisan migrate --force
-          php artisan db:seed --force
+          php artisan migrate:fresh --seed --force
 
       - name: Run Laravel Pint (Code Linting)
         run: php vendor/bin/pint
@@ -92,7 +94,7 @@ jobs:
         run: ls -lah vendor/bin/
 
       - name: Run PHPStan (Static Analysis)
-        run: php vendor/bin/phpstan analyse app/ routes/ database/ --level=max || (echo "PHPStan analysis failed!" && exit 1)
+        run: php vendor/bin/phpstan analyse app/ routes/ database/ --level=5 || (echo "PHPStan analysis failed!" && exit 1)
 
       - name: Run PHPUnit tests
         env:
